apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: jenkins-demo
      app.kubernetes.io/component: jenkins-demo
      app.kubernetes.io/instance: jenkins-demo
    name: jenkins-demo
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deployment: jenkins-demo
    sessionAffinity: None
    type: ClusterIP
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: jenkins-demo
      app.kubernetes.io/component: jenkins-demo
      app.kubernetes.io/instance: jenkins-demo
    name: jenkins-demo
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: jenkins-demo
    template:
      metadata:
        labels:
          app: jenkins-demo
        name: jenkins-demo
      spec:
        containers:
        - image: sv/jenkins-demo:latest
          imagePullPolicy: IfNotPresent
          name: jenkins-demo
          env:
            - name: FAVOURITE_CHEESE
              valueFrom:
                configMapKeyRef: my-configmap
                key: thefavourite.cheese
          ports:
          - containerPort: 8080
            protocol: TCP
        restartPolicy: Always
